//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaDirectMessage_ButDev.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InstaDirectMessage_ButDev.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update!
        ///Error!
        ///License has expired!
        ///The number of threads is incorrect!
        ///The number of IDs for parsing is incorrect!
        ///No proxy file specified!
        ///No account file specified!
        ///No file with user IDs for parsing followers!
        ///The file where you want to save the result is not specified or is specified incorrectly!
        ///Done!
        ///Followers Parser
        ///There is no log file yet!
        ///Followers Parser: Error!
        ///You clicked the &quot;Stop&quot; button.
        ///No hashtag file specified!
        ///Geolocation Parser
        ///Geolocation Parser: Error
        ///Geoloc [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на aa_DJ
        ///aa_ER
        ///aa_ET
        ///af_ZA
        ///am_ET
        ///an_ES
        ///ar_AE
        ///ar_BH
        ///ar_DZ
        ///ar_EG
        ///ar_IN
        ///ar_IQ
        ///ar_JO
        ///ar_KW
        ///ar_LB
        ///ar_LY
        ///ar_MA
        ///ar_OM
        ///ar_QA
        ///ar_SA
        ///ar_SD
        ///ar_SY
        ///ar_TN
        ///ar_YE
        ///as_IN
        ///ast_E
        ///az_AZ
        ///be_BY
        ///ber_D
        ///ber_M
        ///bg_BG
        ///bn_BD
        ///bn_IN
        ///bo_CN
        ///bo_IN
        ///br_FR
        ///bs_BA
        ///byn_E
        ///ca_AD
        ///ca_ES
        ///ca_FR
        ///ca_IT
        ///crh_U
        ///csb_P
        ///cs_CZ
        ///cy_GB
        ///da_DK
        ///de_AT
        ///de_BE
        ///de_CH
        ///de_DE
        ///de_LU
        ///dz_BT
        ///el_CY
        ///el_GR
        ///en_AU
        ///en_BE
        ///en_BW
        ///en_CA
        ///en_DK
        ///en_GB
        ///en_HK
        ///en_IE
        ///en_IN
        ///en_NG
        ///en_NZ
        ///en_PH
        ///en_SG
        ///en_US
        ///en_ZA
        ///en_ZW
        ///es_AR
        ///es_BO
        ///e [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Locales {
            get {
                return ResourceManager.GetString("Locales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось провести обновление!
        ///Ошибка!
        ///Лицензия истекла!
        ///Количество потоков указано некорректно!
        ///Количество ID для парсинга указано некорректно!
        ///Файл с прокси не указан!
        ///Файл с аккаунтами не указан!
        ///Файл с ID конкурентов не указан!
        ///Файл, куда нужно сохранять результат, не указан или указан некорректно!
        ///Завершено!
        ///Парсер подписчиков
        ///Файла с логом пока нет!
        ///Парсер подписчиков: Ошибка!
        ///Вы нажали кнопку &quot;Стоп&quot;.
        ///Файл с хэштегами не указан!
        ///Парсер геолокаций
        ///Парсер геолокаций: Ошибка!
        ///Файл с гео [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ru {
            get {
                return ResourceManager.GetString("ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Instagram 88.0.0.14.99 Android (25/7.1.2; 240dpi; 480x800; HTC/htc_wwe; HTC Vision; vision; vision; en_LS; 149350061)
        ///Instagram 86.0.0.24.87 Android (25/7.1.2; 240dpi; 480x800; LGE/MetroPCS; LGMS323; w5; w5; en_AS; 147375143)
        ///Instagram 77.0.0.20.113 Android (27/8.1.0; 240dpi; 480x800; samsung; GT-S7710; skomer; samsungskomer; en_SH; 139237606)
        ///Instagram 104.0.0.21.118 Android (19/4.4.2; 320dpi; 720x1280; samsung; GT-I9301I; s3ve3g; qcom; en_VI; 165030942)
        ///Instagram 91.0.0.18.118 Android (19/4.4.2; 320dp [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string UserAgentMob {
            get {
                return ResourceManager.GetString("UserAgentMob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
        ///Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
        ///Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362
        ///Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 OPR/57.0.3098.106
        ///Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string UserAgents {
            get {
                return ResourceManager.GetString("UserAgents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на mozilla/5.0 (linux; Android 6.0; neon Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.108 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/171.0.0.49.92;]
        ///mozilla/5.0 (linux; Android 6.0; HUAWEI CUN-L01 Build/HUAWEICUN-L01; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0  Chrome/61.0.3163.98 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/155.0.0.36.96;]
        ///mozilla/5.0 (linux; Android 7.0; 8079 Build/LRX21M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0  Chrome/61.0.3163.98 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string UserAgentsWebAndroid {
            get {
                return ResourceManager.GetString("UserAgentsWebAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.4.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
